services:
 maven-app:
  image: maven:3.8.7-eclipse-temurin-17
  container_name: maven_project1
  working_dir: /app
  volumes:
    - .:/app
    - ~/.m2:/root/.m2
  command: /bin/bash -c "mvn clean package && tail -f /dev/null"
